// Classes and mastery perks. A job is MASTERED at job Lv10; its perk stays with the adventurer forever
// (even after changing jobs), DV2-style. Job levels continue to 99 for small permanent stat growth.
// attack = bow-dependent, innate magic, or innate throw; omitted = melee.
// wt = preferred weapon types (+10% damage, +1 combat speed); all weapons remain usable. range in tiles; heal = support healer; req = mastered prerequisite jobs.

export const TIER_TP = [0, 5, 15, 30, 60];   // Town Points to change into a job of each tier

export const JOBS = {
  // ---- tier 0 ----
  villager: { name: 'Villager', tier: 0, sprites: ['Villager', 'Villager2', 'Villager3', 'Villager4', 'Villager5', 'Woman', 'Boy'],
    hp: 20, atk: 4, def: 3, mag: 1, spd: 1.0, range: 1, weapon: 'Stick', wt: ['sword', 'club', 'staff'], perk: 'allround',
    desc: 'Everyone starts somewhere.' },
  // ---- tier 1 ----
  warrior: { name: 'Warrior', tier: 1, sprites: ['FighterRed', 'FighterWhite'], hp: 34, atk: 8, def: 5, mag: 0, spd: 1.0, range: 1,
    weapon: 'Sword', wt: ['sword', 'axe', 'club'], perk: 'ironbody', desc: 'Sturdy frontliner.' },
  archer: { attack: 'bow', name: 'Archer', tier: 1, sprites: ['Hunter'], hp: 26, atk: 7, def: 3, mag: 1, spd: 1.1, range: 4,
    weapon: 'Bow', wt: ['bow'], perk: 'eagleeye', desc: 'Picks off foes from afar.' },
  mage: { attack: 'magic', name: 'Mage', tier: 1, sprites: ['SorcererBlack', 'SorcererOrange'], hp: 22, atk: 3, def: 2, mag: 9, spd: 0.95, range: 3,
    weapon: 'MagicWand', wt: ['staff', 'book'], perk: 'arcane', desc: 'Fireballs scorch groups.' },
  monk: { attack: 'magic', name: 'Monk', tier: 1, sprites: ['Monk', 'Monk2'], hp: 28, atk: 5, def: 4, mag: 6, spd: 1.0, range: 2, heal: true,
    weapon: 'Book', wt: ['book', 'staff'], perk: 'blessing', desc: 'Heals the party.' },
  brawler: { name: 'Brawler', tier: 1, sprites: ['Caveman', 'Cavegirl', 'Caveman2', 'Cavegirl2'], hp: 38, atk: 9, def: 4, mag: 0, spd: 0.95, range: 1,
    weapon: 'Club', wt: ['club', 'axe', 'hammer'], perk: 'wild', desc: 'Hits like a falling tree.' },
  merchant: { name: 'Merchant', tier: 1, sprites: ['Inspector', 'ManGreen'], hp: 24, atk: 5, def: 4, mag: 3, spd: 1.0, range: 1,
    weapon: 'Rapier', wt: ['rapier', 'whip', 'sword'], perk: 'haggler', desc: 'Finds coin everywhere.' },
  scout: { attack: 'bow', name: 'Scout', tier: 1, sprites: ['Eskimo'], hp: 27, atk: 7, def: 3, mag: 1, spd: 1.2, range: 3,
    weapon: 'Lance2', wt: ['spear', 'bow', 'dagger'], perk: 'pathfinder', desc: 'Fast and far-seeing.' },
  // ---- tier 2 ----
  ranger: { attack: 'bow', name: 'Ranger', tier: 2, sprites: ['CamouflageRed'], hp: 32, atk: 11, def: 5, mag: 2, spd: 1.15, range: 4,
    weapon: 'Bow2', wt: ['bow', 'spear'], perk: 'trailcraft', req: ['archer'], desc: 'A patient hunter of the frontier.' },
  knight: { name: 'Knight', tier: 2, sprites: ['Knight', 'KnightGold'], hp: 46, atk: 9, def: 10, mag: 0, spd: 0.85, range: 1,
    weapon: 'Lance', wt: ['sword', 'spear'], perk: 'guardian', req: ['warrior'], desc: 'A wall of steel.' },
  gladiator: { name: 'Gladiator', tier: 2, sprites: ['GladiatorBlue', 'RedGladiator'], hp: 42, atk: 12, def: 6, mag: 0, spd: 1.0, range: 1,
    weapon: 'Fork', wt: ['sword', 'axe', 'spear', 'trident'], perk: 'showman', req: ['warrior'], desc: 'Fights for the crowd.' },
  ninja: { attack: 'throw', name: 'Ninja', tier: 2, sprites: ['NinjaBlue', 'NinjaRed', 'NinjaGreen', 'NinjaYellow', 'NinjaGray'], hp: 30, atk: 11, def: 4, mag: 2, spd: 1.35, range: 3,
    weapon: 'Ninjaku', wt: ['dagger', 'katana'], perk: 'shadowstep', req: ['archer'], desc: 'Throws shuriken, never stands still.' },
  shaman: { attack: 'magic', name: 'Shaman', tier: 2, sprites: ['Shaman', 'ShamanLion'], hp: 32, atk: 5, def: 5, mag: 10, spd: 1.0, range: 3, heal: true,
    weapon: 'Bone', wt: ['staff', 'bone', 'book'], perk: 'spiritlink', req: ['monk'], desc: 'Talks to beasts and spirits.' },
  onmyoji: { attack: 'magic', name: 'Onmyoji', tier: 2, sprites: ['NinjaMageBlack', 'NinjaMageOrange'], hp: 26, atk: 4, def: 3, mag: 13, spd: 1.05, range: 3,
    weapon: 'MagicWand', wt: ['staff', 'dagger'], perk: 'burn', req: ['mage'], desc: 'Flame talismans that linger.' },
  tamer: { name: 'Beast Tamer', tier: 2, sprites: ['MaskFrog', 'MaskRacoon', 'MaskGoldRacoon'], hp: 34, atk: 9, def: 5, mag: 4, spd: 1.1, range: 2,
    weapon: 'Whip', wt: ['whip', 'spear'], perk: 'tamer', req: ['scout'], desc: 'Monsters want to follow them home.' },
  boxer: { name: 'Boxer', tier: 2, sprites: ['MonkeyBoxerBlue', 'MonkeyBoxerRed', 'Monkey'], hp: 40, atk: 13, def: 5, mag: 0, spd: 1.2, range: 1,
    weapon: 'Sai', wt: ['fist'], perk: 'combo', req: ['brawler'], desc: 'One-two, one-two.' },
  lionheart: { name: 'Lionheart', tier: 2, sprites: ['Lion', 'LionBoy', 'LionOrange', 'LionYellow', 'CaveLion'], hp: 44, atk: 12, def: 7, mag: 1, spd: 1.05, range: 1,
    weapon: 'Hammer', wt: ['axe', 'hammer', 'club'], perk: 'roar', req: ['brawler'], desc: 'Their roar rallies allies.' },
  // ---- tier 3 ----
  sharpshooter: { attack: 'bow', name: 'Sharpshooter', tier: 3, sprites: ['CamouflageGreen'], hp: 38, atk: 17, def: 6, mag: 3, spd: 1.15, range: 5,
    weapon: 'Bow2', wt: ['bow'], perk: 'deadeye', req: ['ranger'], desc: 'Careful aim, decisive shots.' },
  samurai: { name: 'Samurai', tier: 3, sprites: ['Samurai'], hp: 48, atk: 17, def: 8, mag: 0, spd: 1.05, range: 1,
    weapon: 'Katana', wt: ['katana', 'sword'], perk: 'iaido', req: ['knight'], desc: 'One cut, one kill.' },
  master: { name: 'Master', tier: 3, sprites: ['Master'], hp: 50, atk: 16, def: 9, mag: 6, spd: 1.2, range: 1,
    weapon: 'Sai', wt: ['fist', 'staff'], perk: 'enlightened', req: ['boxer'], desc: 'Fists of legend.' },
  royal: { attack: 'magic', name: 'Royal', tier: 3, sprites: ['Princess'], hp: 40, atk: 9, def: 7, mag: 14, spd: 1.0, range: 3,
    weapon: 'Rapier', wt: ['rapier', 'book'], perk: 'royalaura', req: ['onmyoji', 'monk'], desc: 'Commands respect and markets.' },
  sultan: { name: 'Sultan', tier: 3, sprites: ['Sultan'], hp: 42, atk: 12, def: 8, mag: 8, spd: 1.0, range: 1,
    weapon: 'Rapier', wt: ['rapier', 'whip', 'sword'], perk: 'golden', req: ['merchant', 'tamer'], desc: 'Treasure finds its way to them.' },
  assassin: { attack: 'throw', name: 'Assassin', tier: 3, sprites: ['NinjaMasked', 'RedNinja3'], hp: 36, atk: 18, def: 5, mag: 2, spd: 1.4, range: 2,
    weapon: 'Ninjaku', wt: ['dagger', 'katana'], perk: 'execute', req: ['ninja'], desc: 'Strikes from the shadows.' },
  bomber: { attack: 'throw', name: 'Bomber', tier: 3, sprites: ['NinjaBomb'], hp: 34, atk: 14, def: 5, mag: 10, spd: 1.1, range: 3,
    weapon: 'Ninjaku', wt: ['dagger', 'staff'], perk: 'blast', req: ['onmyoji'], desc: 'Everything is a fuse.' },
  vampire: { name: 'Vampire', tier: 3, sprites: ['Vampire'], hp: 44, atk: 13, def: 7, mag: 12, spd: 1.1, range: 1,
    weapon: 'Rapier', wt: ['rapier', 'whip', 'book'], perk: 'lifedrain', req: ['shaman'], desc: 'Drinks the strength of foes.' },
  tengu: { attack: 'throw', name: 'Tengu', tier: 3, sprites: ['Tengu', 'Tengu2'], hp: 40, atk: 14, def: 7, mag: 9, spd: 1.35, range: 2,
    weapon: 'Lance2', wt: ['spear', 'staff'], perk: 'windwings', req: ['ninja', 'monk'], desc: 'Rides the mountain wind.' },
  // ---- tier 4 (legendary) ----
  shogun: { name: 'Shogun', tier: 4, sprites: ['SamuraiBlue'], hp: 62, atk: 22, def: 13, mag: 2, spd: 1.1, range: 1,
    weapon: 'Katana', wt: ['katana', 'sword', 'spear'], perk: 'battlelord', req: ['samurai'], desc: 'A disciplined commander of the front line.' },
  grandmaster: { name: 'Grandmaster', tier: 4, sprites: ['OldMan'], hp: 64, atk: 21, def: 12, mag: 10, spd: 1.25, range: 1,
    weapon: 'Sai', wt: ['fist', 'staff'], perk: 'innerpeace', req: ['master'], desc: 'Perfect form forged through a lifetime of training.' },
  empress: { attack: 'magic', name: 'Empress', tier: 4, sprites: ['Noble'], hp: 52, atk: 12, def: 11, mag: 21, spd: 1.05, range: 3, heal: true,
    weapon: 'Rapier', wt: ['rapier', 'book', 'staff'], perk: 'grace', req: ['royal'], desc: 'A sovereign healer who inspires the guild.' },
  sovereign: { name: 'Golden Sovereign', tier: 4, sprites: ['Sultan2'], hp: 56, atk: 20, def: 12, mag: 15, spd: 1.1, range: 1,
    weapon: 'Rapier', wt: ['rapier', 'whip', 'sword'], perk: 'prosperity', req: ['sultan'], desc: 'Turns perilous expeditions into prosperity.' },
  nightblade: { attack: 'throw', name: 'Nightblade', tier: 4, sprites: ['NinjaDark'], hp: 48, atk: 22, def: 8, mag: 6, spd: 1.45, range: 2,
    weapon: 'Ninjaku', wt: ['dagger', 'katana'], perk: 'veil', req: ['assassin'], desc: 'An elusive master of the killing strike.' },
  warden: { attack: 'bow', name: 'Wildwarden', tier: 4, sprites: ['NinjaEskimo'], hp: 54, atk: 21, def: 10, mag: 9, spd: 1.3, range: 5,
    weapon: 'Bow2', wt: ['bow', 'spear'], perk: 'watchful', req: ['sharpshooter'], desc: 'Guards the wild border with unerring aim.' },
  robot: { name: 'Automaton', tier: 4, sprites: ['RobotGreen', 'RobotGrey', 'RobotCamouflage'], hp: 70, atk: 18, def: 16, mag: 4, spd: 0.9, range: 1,
    weapon: 'Hammer', wt: ['hammer', 'axe'], perk: 'steelframe', req: ['bomber', 'knight'], desc: 'Built to outlast anything.' },
  demon: { attack: 'magic', name: 'Demon', tier: 4, sprites: ['DemonRed', 'DemonGreen'], hp: 55, atk: 12, def: 9, mag: 22, spd: 1.05, range: 3,
    weapon: 'Fork', wt: ['staff', 'book', 'trident'], perk: 'hellfire', req: ['vampire', 'onmyoji'], desc: 'Hellfire answers their call.' },
  skeleton: { name: 'Bone Lord', tier: 4, sprites: ['Skeleton', 'SkeletonDemon'], hp: 60, atk: 20, def: 11, mag: 6, spd: 1.0, range: 1,
    weapon: 'Bone', wt: ['bone', 'sword', 'axe'], perk: 'undying', req: ['gladiator', 'shaman'], desc: 'Death is merely an inconvenience.' },
  spirit: { attack: 'magic', name: 'Spirit', tier: 4, sprites: ['Spirit'], hp: 46, atk: 8, def: 8, mag: 20, spd: 1.3, range: 3, heal: true,
    weapon: 'MagicWand', wt: ['staff', 'book'], perk: 'ethereal', req: ['tengu'], desc: 'Half here, half elsewhere.' },
  legend: { name: 'Legend', tier: 4, sprites: ['GoldStatue'], hp: 72, atk: 22, def: 14, mag: 14, spd: 1.15, range: 1,
    weapon: 'BigSword', wt: ['sword', 'katana', 'axe', 'hammer', 'spear', 'staff', 'book', 'rapier', 'fist', 'dagger', 'club', 'whip', 'bone', 'trident', 'bow'],
    perk: 'legend', req: ['samurai', 'master', 'royal'], desc: 'The village will sing of them.' },
};

// Mastery perks. Numeric fields are read by sim.js via perkSum(); all perks an adventurer has mastered stack.
export const PERKS = {
  trailcraft:  { name: 'Trailcraft',     desc: '+10% movement speed and +5% critical chance.', spdPct: 0.1, crit: 0.05 },
  deadeye:     { name: 'Deadeye',        desc: '+12% ATK and +1 attack range.', atkPct: 0.12, range: 1 },
  battlelord:  { name: 'Battlelord',     desc: '+15% ATK and +10% DEF.', atkPct: 0.15, defPct: 0.1 },
  innerpeace:  { name: 'Inner Peace',    desc: '+15% HP and 10% chance to strike twice.', hpPct: 0.15, doubleHit: 0.1 },
  grace:       { name: 'Imperial Grace', desc: '+15% MAG; heals and potions restore 20% more.', magPct: 0.15, healPct: 0.2 },
  prosperity:  { name: 'Prosperity',     desc: 'Monsters drop 20% more gold; treasure chests appear 25% more often.', goldPct: 0.2, treasurePct: 0.25 },
  veil:        { name: 'Night Veil',     desc: '+10% critical chance and +10% dodge.', crit: 0.1, dodge: 0.1 },
  watchful:    { name: 'Farwatch',       desc: '+15% ATK and +10% movement speed.', atkPct: 0.15, spdPct: 0.1 },
  allround:    { name: 'All-Rounder',    desc: '+5% to every stat.', allPct: 0.05 },
  ironbody:    { name: 'Iron Body',      desc: '+15% max HP.', hpPct: 0.15 },
  eagleeye:    { name: 'Eagle Eye',      desc: '+1 attack range, +8% critical chance.', range: 1, crit: 0.08 },
  arcane:      { name: 'Arcane Surge',   desc: 'Splash damage +50%.', splash: 0.5 },
  blessing:    { name: 'Blessing',       desc: 'Heals and potions restore 30% more.', healPct: 0.3 },
  wild:        { name: 'Wild Strength',  desc: '+12% ATK.', atkPct: 0.12 },
  haggler:     { name: 'Haggler',        desc: 'Monsters drop 25% more gold.', goldPct: 0.25 },
  pathfinder:  { name: 'Pathfinder',     desc: '+15% movement speed.', spdPct: 0.15 },
  guardian:    { name: 'Guardian',       desc: '+20% DEF.', defPct: 0.2 },
  showman:     { name: 'Showman',        desc: 'Each kill adds popularity.', popKill: 0.6 },
  shadowstep:  { name: 'Shadow Step',    desc: '15% chance to dodge attacks.', dodge: 0.15 },
  spiritlink:  { name: 'Spirit Link',    desc: 'Partner monsters bond twice as fast and hit 50% harder.', bondPct: 1.0 },
  burn:        { name: 'Talisman Burn',  desc: 'Attacks set foes alight (+20% damage over time).', burn: 0.2 },
  tamer:       { name: 'Monster Tamer',  desc: 'Defeated monsters join the village twice as often.', tamePct: 1.0 },
  combo:       { name: 'Combo',          desc: '20% chance to strike twice.', doubleHit: 0.2 },
  roar:        { name: 'Rallying Roar',  desc: 'Allies within 3 tiles deal +10% damage.', auraAtk: 0.1 },
  iaido:       { name: 'Iaido',          desc: 'Critical hits deal 2.5x instead of 1.8x.', critMul: 0.7 },
  enlightened: { name: 'Enlightenment',  desc: '+15% EXP from every source.', xpPct: 0.15 },
  royalaura:   { name: 'Royal Aura',     desc: 'While a resident: all village sales +8% (max +25%).', incomePct: 0.08 },
  golden:      { name: 'Golden Touch',   desc: 'Treasure chests appear 50% more often.', treasurePct: 0.5 },
  execute:     { name: 'Assassinate',    desc: '8% chance to finish off a non-boss foe below 30% HP.', execute: 0.08 },
  blast:       { name: 'Blast Radius',   desc: 'Every attack splashes nearby foes for 25%.', splashAll: 0.25 },
  lifedrain:   { name: 'Life Drain',     desc: 'Heals for 15% of damage dealt.', lifesteal: 0.15 },
  windwings:   { name: 'Wind Wings',     desc: '+25% speed and +10% dodge.', spdPct: 0.25, dodge: 0.1 },
  steelframe:  { name: 'Steel Frame',    desc: '+25% HP and +15% DEF.', hpPct: 0.25, defPct: 0.15 },
  hellfire:    { name: 'Hellfire',       desc: '+25% MAG.', magPct: 0.25 },
  undying:     { name: 'Undying',        desc: 'Once per outing, survive a lethal blow at half HP.', revive: 1 },
  ethereal:    { name: 'Ethereal',       desc: '20% dodge; heals restore 20% more. (Dodge caps at 35%.)', dodge: 0.2, healPct: 0.2 },
  legend:      { name: 'Living Legend',  desc: '+15% to every stat and +5% EXP.', allPct: 0.15, xpPct: 0.05 },
};

// Visitor job pool by village stars (visitors arrive with basic jobs; later, some come already advanced).
export const VISITOR_JOBS = [
  ['villager', 'villager', 'warrior', 'archer', 'mage', 'monk'],
  ['villager', 'warrior', 'archer', 'mage', 'monk', 'brawler', 'merchant', 'scout'],
  ['warrior', 'archer', 'mage', 'monk', 'brawler', 'merchant', 'scout', 'knight', 'ninja'],
  ['warrior', 'archer', 'mage', 'monk', 'brawler', 'merchant', 'scout', 'knight', 'gladiator', 'ninja', 'shaman', 'onmyoji', 'tamer', 'boxer', 'lionheart'],
];
