# Bundles v2/js/*.js (ES modules) into ONE classic script (game.js), each module in its own scope,
# and stages a deploy folder containing only what the live game needs.
#
#   python3 v2/tools/bundle.py                 -> <repo>/dist/v2/{index.html, css/style.css, game.js, assets/...}
#   python3 v2/tools/bundle.py --out /some/dir -> /some/dir/{...}
#
# Use it for "paste-only" deploys (GitHub web UI, no git). If the js/ modules are deployed as-is, no bundle is needed:
# GitHub Pages serves ES modules fine. ADD NEW MODULES TO `ORDER` (dependencies first) or they will be missing.
import re, os, shutil, json, sys

ORDER = ['rng', 'path', 'jobs', 'items', 'happenings', 'data', 'world', 'camps', 'relics', 'state', 'sim', 'assets', 'render', 'audio', 'ui', 'main']
V2 = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = sys.argv[sys.argv.index('--out') + 1] if '--out' in sys.argv else os.path.join(os.path.dirname(V2), 'dist', 'v2')

def convert(name, src):
    exports = []
    imported = set()
    for m in re.finditer(r"import\s*\{([^}]*)\}\s*from\s*'\./(\w+)\.js';", src):
        imported.update(n.strip() for n in m.group(1).split(',') if n.strip())
    def imp(m):
        names, mod = m.group(1), m.group(2)
        return f"const {{ {names.strip()} }} = __m['{mod}'];"
    # re-exports: export { A, B } from './x.js';  (names this module also imports are exported, not redeclared)
    def reexp(m):
        names = [n.strip() for n in m.group(1).split(',') if n.strip()]
        exports.extend(names)
        fresh = [n for n in names if n not in imported]
        return f"const {{ {', '.join(fresh)} }} = __m['{m.group(2)}'];" if fresh else ''
    src = re.sub(r"export\s*\{([^}]*)\}\s*from\s*'\./(\w+)\.js';", reexp, src)
    src = re.sub(r"import\s*\{([^}]*)\}\s*from\s*'\./(\w+)\.js';", imp, src)
    def exp(m):
        exports.append(m.group(3)); return m.group(1) + m.group(2)
    def decl(m):
        exports.append(m.group(3))
        # extra declarators on the same line: export const A = 1, B = 2;
        if m.group(2).strip() in ('const', 'let'):
            rest = m.string[m.end():m.string.find('\n', m.end())]
            depth = 0
            for i, ch in enumerate(rest):
                if ch in '([{': depth += 1
                elif ch in ')]}': depth -= 1
                elif ch == ',' and depth == 0:
                    mm = re.match(r"\s*([A-Za-z_$][\w$]*)\s*=", rest[i + 1:])
                    if mm: exports.append(mm.group(1))
        return m.group(1) + m.group(2) + m.group(3)
    src = re.sub(r"^(\s*)export\s+((?:async\s+)?(?:function|const|let|class)\s+)([A-Za-z_$][\w$]*)", decl, src, flags=re.M)
    assert 'import ' not in re.sub(r"//.*", "", src) or name == 'main', f'unconverted import in {name}'
    assert not re.search(r"^\s*export\b", src, re.M), f'unconverted export in {name}'
    return f"// ---- {name}.js ----\n__m['{name}'] = (() => {{\n{src}\nreturn {{ {', '.join(exports)} }};\n}})();\n"

def main():
    base = V2
    parts = ["// Wayfarer Guild v2 — bundled build (generated by v2/tools/bundle.py; edit the modules in v2/js/, never this file).\n'use strict';\nconst __m = {};\n"]
    for n in ORDER:
        parts.append(convert(n, open(f'{base}/js/{n}.js').read()))
    bundle = '(() => {\n' + '\n'.join(parts) + '\n})();\n'
    if os.path.exists(OUT): shutil.rmtree(OUT)
    os.makedirs(f'{OUT}/css', exist_ok=True)
    open(f'{OUT}/game.js', 'w').write(bundle)
    html = open(f'{base}/index.html').read().replace('<script type="module" src="js/main.js"></script>', '<script src="game.js"></script>')
    open(f'{OUT}/index.html', 'w').write(html)
    shutil.copy(f'{base}/css/style.css', f'{OUT}/css/style.css')
    # runtime assets only: atlas, files referenced by HTML/CSS, audio, licenses
    need = set()
    for f in ('index.html', 'css/style.css'):
        for m in re.finditer(r"(?:\.\./)?(assets/[\w/.\- ]+\.(?:png|ttf|mp3))", open(f'{base}/{f}').read()): need.add(m.group(1))
    for d in ('assets/atlas', 'assets/audio/music', 'assets/audio/sfx'):
        for f in os.listdir(f'{base}/{d}'): need.add(f'{d}/{f}')
    for f in os.listdir(f'{base}/assets'):
        if f.endswith('.txt'): need.add(f'assets/{f}')
    for p in sorted(need):
        os.makedirs(os.path.dirname(f'{OUT}/{p}'), exist_ok=True); shutil.copy(f'{base}/{p}', f'{OUT}/{p}')
    print(f'{OUT}: game.js {len(bundle)} bytes; {len(need)} asset files')

main()
